### ISSUE TITLE
 java.lang.ArithmeticException: divide by zero in version 1.2.2

### ISSUE THREAD

**Issue by Serafin-Lopez** [sparrow007/CarouselRecyclerview#21]
java.lang.ArithmeticException: divide by zero
        at com.jackandphantom.carouselrecyclerview.CarouselLayoutManager.onSelectedCallback(CarouselLayoutManager.kt:543)
        at com.jackandphantom.carouselrecyclerview.CarouselLayoutManager.access$onSelectedCallback(CarouselLayoutManager.kt:17)
        at com.jackandphantom.carouselrecyclerview.CarouselLayoutManager$startScroll$2.onAnimationEnd(CarouselLayoutManager.kt:383)
        at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:554)
        at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1250)
        at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1492)
        at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
        at android.animation.AnimationHandler.access$100(AnimationHandler.java:37)
        at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:970)
        at android.view.Choreographer.doCallbacks(Choreographer.java:796)
        at android.view.Choreographer.doFrame(Choreographer.java:727)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:250)
        at android.app.ActivityThread.main(ActivityThread.java:7848)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)

**Comment by sparrow007** [comment]
Hi @Serafin-Lopez thanks for the issue, would you please add steps for reproducing it and anything that helps to know in what situation, you are getting this issue?

**Comment by Serafin-Lopez** [comment]
I am using your library in a CarouselRecyclerview fragment and ReflectionViewContainer adapter, in which I have an interface to open the selected item, to reproduce the problem you have to select the item to see its detail, exit the detail view, scroll to the next items quickly and re-enter another item, repeat this step at least 4 times quickly to play it, I attached a video of how to play it https://drive.google.com/file/d/1gSLJ5v7oieKbdDoXqJHv-ek13MTDpdsV/view?usp=sharing

**Comment by sparrow007** [comment]
@Serafin-Lopez thank you for this information, I'll apply these steps that will really help to resolve this issue. will update you about issue regularly. thanks 👍

**Comment by sparrow007** [comment]
Hi i am done with fix, will release new version for the lib so i will reply on same issue when i done with release on maven

**Comment by sparrow007** [comment]
Hi @Serafin-Lopez can try with     implementation 'com.github.sparrow007:carouselrecyclerview:1.2.3'
and check the issue.

**Comment by sparrow007** [comment]
@Serafin-Lopez Please use jitpack for the newly updated library, read the readme for the updated library.

**Comment by Serafin-Lopez** [comment]
Hi @sparrow007 I have tried the new implementation version 'com.github.sparrow007:carouselrecyclerview:1.2.3' and the error continues I have reproduced it in the same way as in the video


E/AndroidRuntime: FATAL EXCEPTION: main
    Process: mx.com.qualitycode.sona, PID: 6736
    java.lang.ArithmeticException: divide by zero
        at com.jackandphantom.carouselrecyclerview.CarouselLayoutManager.onSelectedCallback(CarouselLayoutManager.kt:543)
        at com.jackandphantom.carouselrecyclerview.CarouselLayoutManager.access$onSelectedCallback(CarouselLayoutManager.kt:17)
        at com.jackandphantom.carouselrecyclerview.CarouselLayoutManager$startScroll$2.onAnimationEnd(CarouselLayoutManager.kt:383)
        at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:554)
        at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1250)
        at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1492)
        at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
        at android.animation.AnimationHandler.access$100(AnimationHandler.java:37)
        at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:970)
        at android.view.Choreographer.doCallbacks(Choreographer.java:796)
        at android.view.Choreographer.doFrame(Choreographer.java:727)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:250)
        at android.app.ActivityThread.main(ActivityThread.java:7848)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)

**Comment by Serafin-Lopez** [comment]
![image](https://user-images.githubusercontent.com/70175440/151722436-a2f3a6f0-19ac-44a6-bd08-5f337632ed99.png)

**Comment by Serafin-Lopez** [comment]
https://github.com/Serafin-Lopez/CarouselRecyclerviewExampleIssue.git  I have created an example as I use it in my project, so you can review the issue in greater detail, thanks

**Comment by sparrow007** [comment]
@Serafin-Lopez Thanks this is a big help, I'll look into this and fix it accordingly.

**Comment by Serafin-Lopez** [comment]
@sparrow007 the problem was resolved in the implementation version 'com.github.sparrow007:carouselrecyclerview:1.2.3', the issue was caused by the view model I have updated the example and there are no more problems about the issue, thank you very much

**Comment by sparrow007** [comment]
@Serafin-Lopez really happy to see that issue is got resolved, thanks for providing and giving help (we both solve it)😊
