### ISSUE TITLE
Adapter.notifyItemChanged(int) causes it to crash

### ISSUE THREAD

**Issue by mice777** [sparrow007/CarouselRecyclerview#28]
```
    java.lang.NullPointerException
        at com.jackandphantom.carouselrecyclerview.CarouselLayoutManager.getChildActualPos(CarouselLayoutManager.kt:468)
        at com.jackandphantom.carouselrecyclerview.CarouselRecyclerview.getChildDrawingOrder(CarouselRecyclerview.kt:106)
        at android.view.ViewGroup.getAndVerifyPreorderedIndex(ViewGroup.java:1733)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3510)
        at android.view.View.draw(View.java:17192)
        at androidx.recyclerview.widget.RecyclerView.draw(RecyclerView.java:4429)
        at android.view.View.updateDisplayListIfDirty(View.java:16171)
        at android.view.View.draw(View.java:16955)
...
```

**Comment by sparrow007** [comment]
@mice777 Thanks please check new version of the library for the fix
